// Icon type definitions for the SyncPulse design system
export type IconName =
  | 'home'
  | 'settings'
  | 'user'
  | 'logout'
  | 'menu'
  | 'close'
  | 'search'
  | 'filter'
  | 'sort'
  | 'refresh'
  | 'edit'
  | 'delete'
  | 'copy'
  | 'download'
  | 'upload'
  | 'share'
  | 'favorite'
  | 'bookmark'
  | 'alert'
  | 'info'
  | 'success'
  | 'error'
  | 'warning'
  | 'check'
  | 'checkmark'
  | 'cross'
  | 'plus'
  | 'minus'
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'external-link'
  | 'link'
  | 'help'
  | 'clock'
  | 'calendar'
  | 'bell'
  | 'mail'
  | 'phone'
  | 'lock'
  | 'unlock'
  | 'visibility'
  | 'visibility-off'
  | 'code'
  | 'terminal'
  | 'github'
  | 'agents'
  | 'swarm'
  | 'agent-active'
  | 'agent-idle'
  | 'agent-error'
  | 'play'
  | 'pause'
  | 'stop';

export interface IconProps {
  name: IconName;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  color?: string;
  className?: string;
  weight?: 'light' | 'regular' | 'bold';
}
